language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: AnAj2g1IPHupvDfGt9XXhtVk+9vP6xdakg184Xw8M7pSmjkmRV3/e+Wk8rqgD2NBRhJ7S94mWaAsWmg0pQM3+Kw5XSbKK4fYxveSW0pRoE1vtnaUWRNlqxTifB+MK+Rt0iwbQ9+nAJvUt18l3kZxysH0kOwWBjFAv2upqBPcDgdRSx239NDQmaZqA8WrTIKR67YHLABBQBT78vdcYXPmelHMTn1vB+2y0k/14iirwp9n537bmHhcUS/lfoBx5YlXWHVaXcdIUrhyhl7KnYopypH0/kkhSSUccVuoLfM9vdhe9RNsKe7iWpth54DNBZsRr29DyNcll48m1cWh1TVpmjtasH1o0k+nW0ttfsxstNZsw4Lhmo9MY7GWEYogYmIbDIDETcllJtBpOFslRVssTmBuL0/gfLPc8CN3+F8gBFzb4VVhFZC2VQIeqjk5UlAfxDdtMsrAVAXGmOI6k7LbA6cTikCA+U/M8zuzeNnNxCwTqqDPbi2BgigQyfFirtVr/QnWGVfTbfpkNEZ86iIDVQKWcu1tAu73Rg46MmeKJXDzMLbUZLhM2qDuO6vdS9MtbaqLNHUsCEEptBW3pN/0tPMmKL1NDQLEcoq3eqk/mJVEh80mI8AU0j3d9N75Wkgd3DnBWR4GB/DquavJTxC4bhW5VR3TWqk/XCrbsMYZ40U=
